detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - "Location"
  UncommunicativeParameterName:
    exclude:
      - "Location#initialize"