detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeParameterName:
    exclude:
      - "Coordinates"
  UncommunicativeVariableName:
    exclude:
      - "Coordinates"
  FeatureEnvy:
    exclude:
      - "Coordinates#=="
