detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - "Position"
  UncommunicativeParameterName:
    exclude:
      - "Position#initialize"