name: run-automated-tests
run-name: Run programmer tests for the kata
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - run: bundle install
      - run: bundle exec rspec -cfd